esphome:
  name: teams-status-light
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "FallbackHotspot"

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_pass

logger:
ota:

output:
  - platform: gpio
    pin: GPIO2
    id: status_led

text_sensor:
  - platform: mqtt_subscribe
    name: "Teams Mic"
    id: mic_status
    topic: "teams/microphone"
    on_value:
      then:
        - lambda: |-
            if (x == "active") {
              id(status_led).turn_on();
            } else {
              id(status_led).turn_off();
            }

  - platform: mqtt_subscribe
    name: "Teams Camera"
    id: cam_status
    topic: "teams/camera"
